spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ecomm
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8080
