spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: ecomm
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8080
