spring:
  datasource:
    username: ss_tester
    url: jdbc:postgresql://103.209.147.187:5432/ss_ecomm_db
    password: Bubble@12
  jpa:
    properties:
      hibernate:
        default_schema: ecomm
    show-sql: true
    hibernate:
      ddl-auto: none
server:
  port: 8080
