spring:
  jpa:
    properties:
      hibernate:
        default_schema: ecomm
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: none
server:
  port: 8080
